name: appstream
version: 0.2.4

description:
  A parser for Appstream data.
  This package allows Dart applications to access package metadata on Linux systems.

homepage: https://github.com/canonical/appstream.dart

environment:
  sdk: '>=2.14.0 <3.0.0'

platforms:
  linux:

dependencies:
  xml: ^5.1.1
  # Appstream YAML is broken on Ubuntu - use a fork
  yaml_appstream_workaround:
    path: packages/yaml_appstream_workaround

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
